projects:
  Codegen Project:
    schemaPath: schema.graphql
    includes:
      - src/graphql
    excludes:
      - ./amplify/**
      - src/services/api/graphqlAPI
      - src/services/api/graphqlAPI.ts
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/services/api/graphqlAPI.ts
        docsFilePath: src
        region: us-east-1
        apiId: null
        frontend: javascript
        framework: react
        maxDepth: 2
extensions:
  amplify:
    version: 3
